FROM node:16-alpine
WORKDIR '/app'
ENV CI=true
ENV WDS_SOCKET_PORT=0

WORKDIR "/app"
COPY ./package.json ./
RUN npm install 
RUN mkdir -p node_modules/.cache && chmod -R 777 node_modules/.cache
RUN npm install
COPY . .
CMD ["npm", "run", "start"]