sudo: required
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD) # Getting git commit SHA and storing it as an env var
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1 # Disable google cloud cli prompts
    - CLOUDSDK_PYTHON="3.10"
before_install:
  - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d # Get and decrypt the encrypted service account file for google cloud
  - curl https://sdk.cloud.google.com | bash > /dev/null; # Download google cloud sdk
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl # Update kubectl command
  - gcloud auth activate-service-account --key-file service-acount.json # Use decrypted json file to login to google cloud account
  - gclound config set project multi-k8s-430010 # Name of the project (ID on google cloud console)
  - gcloud config set compute/zone europe-central2-a # Use compute zone as the k8s cluster created on google cloud
  - gcloud container clusters get-credentials multi-cluster # Provide the name of the cluster
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin # Login to docker (Env variables are stored in Travis CI)
  - docker build -t toxiczeina/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true toxiczeina/react-test npm test # Run tests and pass -e CI=true to exit tests

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
